# tomcat端口号
server:
  port: 8090

#数据连接配置信息
spring:
  datasource:
    name: seafarer_recruitment
    url: jdbc:mysql://172.81.209.8:3306/seafarer_recruitment?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Tx20220311!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20


  redis:
    host: 172.81.209.8
    port: 6379
    database: 0
    password: redis123456
    timeout: 5000


mybatis-plus:
  # Mapper.xml存放位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号隔开
  type-aliases-package: com.lhh.print.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


    # 七牛云配置
qiniu.access-key: M8sFrz2YGzuqMoLNuG4i7oYfuvVl9_y-GtuAvmUc
qiniu.secret-key: soWDryK19oFsiglgSJFHQyQDNOfWn1YkGZjnV6XV
qiniu.bucket: proj-haiyuan
 # [{'zone0':'华东'}, {'zone1':'华北'},{'zone2':'华南'},{'zoneNa0':'北美'},{'zoneAs0':''}]
qiniu.zone: zone2
qiniu.domain-of-bucket: r9wgzpaah.hn-bkt.clouddn.com
 # 链接过期时间，单位是秒，3600代表1小时，-1代表永不过期
qiniu.expire-in-seconds: -1